### ISSUE TITLE
[feature-request] Enable class based method hooks

### ISSUE THREAD

**Issue by DonnC** [DonnC/pywce#3]
Currently supported hooks are function based hooks.

It could make sense to support OOP, where some business logic might be in a certain class

Consider the approach like below

```python
# example.hooks.todo.py
class ToDo(AbstractHookArgCls):
    # overriden to initiate current user arg
    def setup_args(self, arg: HookArg):
        self.arg = arg

    def save_todo(self):
       todo = self.arg.user_input
       self.db.save(todo)
       return self.arg
    
    # ..
````

Calling the hook in template
```yaml
"SAVE-TODO-STAGE":
    type: text
    message: Enter the new todo
    on-receive: example.hooks.todo:ToDo.save_todo
    routes:
       "re:.*": "VIEW-TODOS-STAGE"

```
